spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo_secret_psw
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/demo
    user: demo
    password: demo_secret_psw
    schemas: public
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: false # When true it permit initializing a non-empty schema, but the db migration version needs to be shifted by 1
    clean-disabled: false # Useful in development env, not safe in prod

# App Properties
playground:
  app:
    jwtSecret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000