server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always

management:
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus, gateway