CREATE TABLE students
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE teachers
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_teacher PRIMARY KEY (id)
);

CREATE TABLE teachers_students
(
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    CONSTRAINT pk_teachers_students PRIMARY KEY (student_id, teacher_id)
);

ALTER TABLE teachers_students
    ADD CONSTRAINT fk_teastu_on_student FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE teachers_students
    ADD CONSTRAINT fk_teastu_on_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id);


DROP view IF EXISTS teacher_student_view;
create view teacher_student_view as
select t.id, t.name AS teacher_name, s.name AS student_name
from teachers t
         join teachers_students ts on t.id = ts.teacher_id
         join students s on ts.student_id = s.id;

