CREATE TABLE student
(
    student_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_name VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (student_id)
);

CREATE TABLE teacher
(
    teacher_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_name VARCHAR(255),
    CONSTRAINT pk_teacher PRIMARY KEY (teacher_id)
);

CREATE TABLE teachers_students
(
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    CONSTRAINT pk_teachers_students PRIMARY KEY (student_id, teacher_id)
);

ALTER TABLE teachers_students
    ADD CONSTRAINT fk_teastu_on_student FOREIGN KEY (student_id) REFERENCES student (student_id);

ALTER TABLE teachers_students
    ADD CONSTRAINT fk_teastu_on_teacher FOREIGN KEY (teacher_id) REFERENCES teacher (teacher_id);


DROP view IF EXISTS teacher_student_view;
create view teacher_student_view as
select t.teacher_id, t.teacher_name, s.student_name
from teacher t
         join teachers_students ts on t.teacher_id = ts.teacher_id
         join student s on ts.student_id = s.student_id;

